fix: try simpler pipe with true

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -12,15 +12,10 @@ jobs:
       - run:
           name: "Run Jest and Collect Coverage Reports"
           command: |
-            cleanup() {
-                echo "Trap coverage threshold failure for now, due to parallelism constraints."
-                trap 'exit 0' EXIT
-            }
-            trap cleanup EXIT
-
             TESTFILES=$(circleci tests glob "./*.test.js" | circleci tests split --split-by=timings)
             echo $TESTFILES
-            npx jest --coverageDirectory="coverage/${CIRCLE_NODE_INDEX}" $TESTFILES
+            # workaround: `|| true` to ensure coverage failures still exit 0
+            npx jest --coverageDirectory="coverage/${CIRCLE_NODE_INDEX}" $TESTFILES || true
       - store_artifacts:
           path: coverage
       - persist_to_workspace:
